# Site
title:              Sihan's Blog
bio:                'Wir müssen wissen, Wir werden wissen.'
description:        "Wir müssen wissen, Wir werden wissen."
reading_time:       true
words_per_minute:   200
logo:               'assets/img/unicorn.jpg'
background:         'assets/img/placeholder-big.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                https://sihan-son.github.io
#url: localhost:4000

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   sihans-blog-1

# Social
# if you don't have any of social below, comment the line.
google:
  #plus:            #username
  analytics: UA-143237170-1
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
email:              sihan830@gmail.com
#twitter:            username
facebook:           sihan830
github-url:         Sihan-Son
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
#linkedin:          username
#xing:              username
instagram:          sihan_k_son
#lastfm:            username
#tumblr:            username
#medium:            '@username'
#pinterest:         username
#foursquare:        username
steam:              sihan830
#dribbble:          username
#youtube:           username
#youtube-channel:   channel
soundcloud:        sihan-son
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com
      #https://github.com/TaylanTatli/Moon

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
